name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # or adopt/openjdk/zulu etc.
          java-version: '11'

      - name: Build with Maven
        run: mvn -B clean verify

      - name: Test with Maven
        run: mvn test -X

      - name: Package
        run: mvn clean package